[package]
name = "slide"
version = "0.2.0"
authors = ["Noskcaj <kcajdev@gmail.com>"]
edition = "2018"

[dependencies]
rug = "1.2.2"
lalrpop-util = "0.16.1"
liner = "0.4.4"
termion = "1.5.1"

[dependencies.parsing]
path = "parsing"
