[package]
name = "slide"
version = "0.2.0"
authors = ["Noskcaj <kcajdev@gmail.com>"]
edition = "2018"

[build-dependencies] 
lalrpop = "0.16.1" 

[dependencies]
rug = "1.2.2"
lalrpop-util = "0.16.1"
regex = "1.0.5"
liner = "0.4.4"
termion = "1.5.1"
pest = "2.0.2"
pest_derive = "2.0.1"
