[package]
name = "parsing"
version = "0.1.0"
authors = ["Noskcaj <kcajdev@gmail.com>"]
edition = "2018"

[dependencies]
pest = "2.0.2"
pest_derive = "2.0.1"
lalrpop-util = "0.16.1"
regex = "1.0.5"
rug = "1.2.2"

[build-dependencies]
lalrpop = "0.16.1"
